### ISSUE TITLE
rnaseq.Rmd changes to target v1.6

### ISSUE THREAD

**Issue by daler** [lcdb/lcdb-wf#276]
This issue collects various other issue related to the rnaseq.Rmd updates, organizing them by broad section in rnaseq.Rmd.

## Ingest files from the upstream workflow
- [ ] use transcript-to-gene mappings (and possibly gene_id to symbol mappings) generated from GTF (#177)

## Create initial dds object, vst, and QC
- [ ] use salmon rather than featurecounts (#271)
- [ ] helper function for removing batch effects (#255)
- [ ] helper function for ranking raw log2foldchange between arbitrary samples (#256)
- [ ] generalize size factor plots (#251)
- [ ] include code for running sva (#272)

## Create dds objects used for DE
- [ ] streamline the process of collapsing techreps and removing Ensembl versions (#275)

## Build the results
- [ ] add more contrast examples to the comments, like character and numeric vector formats (#268)
- [ ] improve the "top.plots" plotting functionality (#224)
- [ ] explicitly use `apeglm` for lfcShrink, and figure out how to adjust models appropriately (#273)

## Summarize and plot the results
- [ ] unify how FDR and LFC are configured and passed around (#267)
- [ ] plotting improvements (#266)

## Export results
- [ ] improve and expand the exported output (#257, may take some coordination with #274)

## Gene patterns
- [x] split off into new Rmd (#259)
- [ ] ensure degPatterns chunk uses the same alpha and lfc.thresh criteria as elsewhere (#269)
- [ ] attach cluster IDs to the differential expression output (#274)

## Functional enrichment analysis
- [x] split off into new Rmd (#259)
- [ ] parallelize clusterProfiler (#233)
- [ ] provide option to toggle GSEA or overrepresentation (#262)
